export const pagesRoutes = [
  ["v-3399e2c5","/100-before.html",{"title":"Preparatory work for docking"},[":md"]],
  ["v-8daa1a0e","/",{"title":"Energy Development Documentation"},["/README.md"]],
  ["v-744497ce","/api/",{"title":""},["/api/README.md"]],
  ["v-41f21194","/api/api-summary.html",{"title":"API usage summary"},[":md"]],
  ["v-48c74aa6","/api/index-data.html",{"title":"Public data query"},[":md"]],
  ["v-eb3c4c94","/api/order-auto-policy.html",{"title":"Smart Delegate"},[":md"]],
  ["v-0186f65c","/api/order-collect.html",{"title":"Collection API"},[":md"]],
  ["v-43691edc","/api/order-count-policy.html",{"title":"Purchase by number of transfers"},[":md"]],
  ["v-69422f50","/api/order-create.html",{"title":"Place an order"},[":md"]],
  ["v-4087f520","/api/order-expiring.html",{"title":"Expired orders soon"},[":md"]],
  ["v-26ddce46","/api/order-price.html",{"title":"Estimated order amount"},[":md"]],
  ["v-175dbc37","/api/order-process.html",{"title":"Order in progress"},[":md"]],
  ["v-39c188be","/api/order-query.html",{"title":"Order query (single)"},[":md"]],
  ["v-373201ed","/api/order-recliam.html",{"title":"Order recycling (single)"},[":md"]],
  ["v-e2185298","/api/order-transfer-trx.html",{"title":"Transferring small amounts of TRX"},[":md"]],
  ["v-4290fe40","/general/",{"title":"description"},["/general/README.md"]],
  ["v-403dad74","/general/callback.html",{"title":"callback"},[":md"]],
  ["v-10ca7972","/general/error-code.html",{"title":"API return value"},[":md"]],
  ["v-659b0a08","/general/sign.html",{"title":"How to sign"},[":md"]],
  ["v-54fd0694","/zh/100-before.html",{"title":"对接的准备前工作"},[":md"]],
  ["v-2d0ad528","/zh/",{"title":"能量 开发文档"},["/zh/README.md"]],
  ["v-6cda9c6a","/ru/100-before.html",{"title":""},[":md"]],
  ["v-2d0ab8b3","/ru/",{"title":"https://{domain} Документация по разработке"},["/ru/README.md"]],
  ["v-e4cb1150","/other/",{"title":""},["/other/README.md"]],
  ["v-c670379c","/other/auto.html",{"title":"Smart hosting"},[":md"]],
  ["v-53f9ca7d","/zh/api/",{"title":"接口"},["/zh/api/README.md"]],
  ["v-69220643","/zh/api/api-summary.html",{"title":"API使用汇总"},[":md"]],
  ["v-187e8417","/zh/api/index-data.html",{"title":"公共数据查询"},[":md"]],
  ["v-27a561b6","/zh/api/order-auto-policy.html",{"title":"智能委托"},[":md"]],
  ["v-1c8c7b4b","/zh/api/order-collect.html",{"title":"归集API"},[":md"]],
  ["v-1b0c574d","/zh/api/order-count-policy.html",{"title":"转账笔数购买"},[":md"]],
  ["v-2810d081","/zh/api/order-create.html",{"title":"下单"},[":md"]],
  ["v-25671e61","/zh/api/order-expiring.html",{"title":"即将到期订单"},[":md"]],
  ["v-13c10d8c","/zh/api/order-price.html",{"title":"下单预估金额"},[":md"]],
  ["v-32634126","/zh/api/order-process.html",{"title":"进行中的订单"},[":md"]],
  ["v-60f17d6d","/zh/api/order-query.html",{"title":"订单查询（单个）"},[":md"]],
  ["v-523786dc","/zh/api/order-recliam.html",{"title":"订单回收（单个）"},[":md"]],
  ["v-66970f25","/zh/api/order-transfer-trx.html",{"title":"代转小额TRX"},[":md"]],
  ["v-09ff416f","/zh/general/",{"title":"说明"},["/zh/general/README.md"]],
  ["v-01e762b6","/zh/general/callback.html",{"title":"回调"},[":md"]],
  ["v-3d45dc38","/zh/general/error-code.html",{"title":"API返回值"},[":md"]],
  ["v-d8c946a6","/zh/general/sign.html",{"title":"如何签名"},[":md"]],
  ["v-54cdba47","/zh/other/",{"title":""},["/zh/other/README.md"]],
  ["v-3eaf7e23","/zh/other/auto.html",{"title":"智能托管"},[":md"]],
  ["v-7a121ef0","/ru/api/",{"title":"Интерфейс"},["/ru/api/README.md"]],
  ["v-27409364","/ru/api/api-summary.html",{"title":"Сводка по использованию API"},[":md"]],
  ["v-efd5b2a8","/ru/api/index-data.html",{"title":"Общий запрос данных"},[":md"]],
  ["v-4768ea20","/ru/api/order-auto-policy.html",{"title":"Интеллектуальная делегация"},[":md"]],
  ["v-71c356d4","/ru/api/order-collect.html",{"title":"API для коллекции средств"},[":md"]],
  ["v-2eb594e2","/ru/api/order-count-policy.html",{"title":"Покупка количества транзакций"},[":md"]],
  ["v-0c8921d6","/ru/api/order-create.html",{"title":"Оформление заказа"},[":md"]],
  ["v-65df2314","/ru/api/order-expiring.html",{"title":"Срок действия заказов скоро закончится"},[":md"]],
  ["v-d20284d2","/ru/api/order-price.html",{"title":"Оценка стоимости заказа"},[":md"]],
  ["v-4615cb1e","/ru/api/order-process.html",{"title":"Заказ в процессе"},[":md"]],
  ["v-37a1a510","/ru/api/order-query.html",{"title":"Поиск заказа (один)"},[":md"]],
  ["v-066d3fb2","/ru/api/order-recliam.html",{"title":"Восстановление заказа (один)"},[":md"]],
  ["v-7a404cba","/ru/api/order-transfer-trx.html",{"title":"Трансфер небольших сумм TRX"},[":md"]],
  ["v-0dccecdc","/ru/other/",{"title":""},["/ru/other/README.md"]],
  ["v-32c0b338","/ru/other/auto.html",{"title":"Умное управление"},[":md"]],
  ["v-6ad72c0c","/ru/general/",{"title":"Инструкция"},["/ru/general/README.md"]],
  ["v-38f6c00c","/ru/general/callback.html",{"title":"Обратный вызов"},[":md"]],
  ["v-3621a766","/ru/general/error-code.html",{"title":"API возвращаемые значения"},[":md"]],
  ["v-6f98befc","/ru/general/sign.html",{"title":"Как подписывать запросы"},[":md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
]
